Сделал вывод списка всех айдишников на сегодняшнюю дату
Move-Fast-and-Break-Things-Study-Group/the-list pull request #20
Opened 2022-10-05 09:27 UTC by Roha990

## Что делает этот PR?

Сделал добавление и вывод списка ID студентов на дату.

## Ограничения

Пока есть два ограничения: 
- Добавляются ВСЕ ID студентов, находящихся в базе данных `students`.
- Дата выставляется сегодняшнего дня.

В будущем все эти проблемы будут исправляться. Дату можно будет поставить вручную, а студентов можно будет добавлять по отдельности, а не всех сразу.

## Как тестировать?

Для начала, в базе данных должны быть хоть какие-то студенты.
Для добавления студентов на сегодняшнюю дату делаете запрос в инсомнии `POST/'http://localhost:4000/students/date'`.
Для вывода списка студентов на сегодняшнюю дату делаете запрос в инсомнии `GET/'http://localhost:4000/students/date'`.

## Чеклист

- [ ] мой PR сфокусирован и содержит одно логически цельное изменение
- [ ] я протестировал(а) PR локально и убедился(ась) в том, что он работает
- [ ] если моё изменение содержит изменения интерфейса, я вставил(а) в описание скриншот или скринкаст

2022-10-07 07:19 UTC, yurijmikhalevich reviewed
Можешь, пожалуйста, отрибейзить свою ветку на последний коммит в `master` и сделать `yarn lint:fix`?

2022-10-08 16:36 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
> +// @ts-nocheck
В этом не должно быть необходимости.

```suggestion
```

2022-10-09 15:59 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  const FindStudentsInDate = await dailyAttendance.find({date: ctx.params.date}).toArray();
Т.к. мы знаем, что запись с посещаемостью для каждого дня в БД одна, мы можем  делать `findOne` и убрать `toArray`.

```suggestion
  const FindStudentsInDate = await dailyAttendance.findOne({date: ctx.params.date});
```

2022-10-09 16:01 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  const check = await dailyAttendance.find({date: ctx.params.date}).toArray();
Тоже самое, что и ниже. Можно использовать `findOne`.

2022-10-09 16:09 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  );
Этот метод позволяет добавлять студентов, но не позволяет их удалять.

Идея, которую я предложил [тут](https://github.com/Move-Fast-and-Break-Things-Study-Group/the-list/issues/18#issuecomment-1271202632) заключается в том, что `PUT` запрос должен принимать не один айдишник, а айдишники всех студентов за сегодняшний день и просто перезаписывать старый список в БД. Таким образом, методом `PUT` можно будет и удалять и добавлять студентов.

Если ты хочешь добавлять студентов по одному (твоя реализация отличная и такой метод приводит к отправке меньшего объёма данных 👍), то нам нужно будет запрограммировать и логику удаления инфе о посещаемости студентов для конкретного дня. Можно добавить метод вроде `DELETE /attendance/:date`.

Или сделать единый `PATCH /attendance/:date` с body:
```js
{
  studentId: string;
  action: 'add' | 'remove';
}
```

Если надо добавить студента, то присылать:
```json
{
  "studentId": "abcdef3234234234",
  "action": "add"
}
```

А если удалить:
```json
{
  "studentId": "abcdef3234234234",
  "action": "remove"
}
```

Идея с единым `PATCH` мне нравится больше. Что ты думаешь?

2022-10-09 16:13 UTC, yurijmikhalevich commented on the-list-be/server.js
> +router.post('/student', async ctx => {
Это мелочь, но обычно когда делают API для работы с какой-то сущностью, например студент, то все методы для работы с этой сущностью называют одинаково, например:
- `GET /students` — возвращает всех студентов
- `DELETE /students/:id` — удаляет конкретного
- `POST /students` — добавляет нового студента (student**s** даже несмотря на то, что добавляем одного студента)

Если использовать одно имя для работы с одной сущностью, то их проще группировать, искать их использование в коде, собирать аналитику, связанную с использованием этой сущности, и т.д.

```suggestion
router.post('/students', async ctx => {
```

2022-10-09 19:42 UTC, Roha990 commented on the-list-be/server.js
> +  );
Да, я задумывался над тем, чтобы несколько студентов можно было одновременно добавлять в список, но передумал.

Метод `DELETE` у меня как раз в планах, его я реализую чуть позже

2022-10-09 19:43 UTC, Roha990 commented on the-list-be/server.js
> +  const FindStudentsInDate = await dailyAttendance.find({date: ctx.params.date}).toArray();
А чем `findOne` отличается от `find`?

2022-10-09 20:45 UTC, Roha990 commented on the-list-be/server.js
> +  );
Ладно, я передумал делать через `DELETE`. Хочу попробовать другой метод, считаю, лишним не будет.

Как мне это реализовать через `PATCH`? Тут будет какой-то условный оператор?

2022-10-10 07:04 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  const FindStudentsInDate = await dailyAttendance.find({date: ctx.params.date}).toArray();
@Roha990, `findOne` возвращает первый документ, соответствующий запросу, `find` — возвращает все. Если документов, соответствующих запросу, в БД несколько или если нет уникального индекса на поле, по которому мы ищем, `findOne` будет работать быстрее, т.к. перестанет перебирать БД после того, как найдёт первый подходящий документ. В общем случае, когда нам нужен только один документ, лучше использовать `findOne`.

2022-10-10 07:05 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  );
@Roha990, да. В зависимости от того, равен `action` `'add'` или `'remove'`, ты можешь делать операцию `$addToSet` или `$pull` (обратная `$addToSet`).

2022-10-10 12:44 UTC, OstaptsovDanil requested changes
не нравится, переделывай

2022-10-10 12:45 UTC, OstaptsovDanil commented
Шучу, вечером посмотрю

2022-10-10 17:43 UTC, EmmaMaltseva reviewed
Сейчас ознакомлюсь с кодом и задам вопросы

2022-10-10 17:43 UTC, EmmaMaltseva commented on the-list-be/server.js
> +    (todayDate.getMonth() + 1) +
Почему здесь +1?

2022-10-10 17:44 UTC, EmmaMaltseva commented on the-list-be/server.js
> +      { $pull: { students: ctx.request.body._id } }
Откуда мы взяли $pull и $addToSet? Поясни строчки 19, 25)

2022-10-10 18:13 UTC, Roha990 commented on the-list-be/server.js
> +      { $pull: { students: ctx.request.body._id } }
`$addToSet` и `$pull` - это опции updateOne.
`$addToSet` добавляет в массив новое значение и не повторяется(т.е, если в массиве есть к примеру "Emma" и мы попытаемся туда добавить "Emma", то у нас ничего не получится, ведь значения с помощью `addToSet` не повторяются при добавление)
`$pull` удаляет значение из массива

Документация - https://www.mongodb.com/docs/manual/reference/method/db.collection.update/

2022-10-10 18:25 UTC, Roha990 commented on the-list-be/server.js
> +    (todayDate.getMonth() + 1) +
Это лишняя часть кода, но метод `getMonth` возращает значение от 0 до 11, т.е если у нас будет 11 месяц, то `getMonth` вернет 10

2022-10-10 18:50 UTC, KogayIrina requested changes

2022-10-10 18:50 UTC, KogayIrina commented on the-list-be/server.js
> +  const check = await dailyAttendance.findOne({ date: ctx.params.date });
Переменная названа неверно, из названия не понятно что в ней содержится.
findOne вернет тебе список студентов на определенный день, это должно быть понятно из названия переменной.

2022-10-10 18:50 UTC, KogayIrina commented on the-list-be/server.js
> +  const FindStudentsInDate = await dailyAttendance.findOne({
То же самое, что с переменной check. Название переменной в данном случае — глагол, а должно быть существительное.

2022-10-10 18:50 UTC, KogayIrina commented on the-list-be/server.js
> +  const findStudents = await students.find({}).toArray();
здесь ты выбираешь всех студентов, лучше бы назвать переменную allStudents

2022-10-10 18:50 UTC, KogayIrina commented on the-list-be/server.js
> +  const insertStudent = await students.insertOne(ctx.request.body);
то же самое, переменная — глагол, а не существительное

2022-10-10 18:50 UTC, KogayIrina commented on the-list-be/server.js
> +  const deleteStudent = await students.deleteOne({
название переменной некорректное

2022-10-10 18:50 UTC, KogaiIrina commented on the-list-ui/src/App.js
> +        >
лишний пробел

2022-10-11 14:36 UTC, KogayIrina submitted a review, later dismissed

2022-10-11 16:21 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  if (ctx.request.body.action == 'remove') {
```suggestion
  } else if (ctx.request.body.action == 'remove') {
```

А что произойдёт, если я передам `"action": "random string"`? Надо, в этом случае, адекватную ошибку на клиент отправить.

2022-10-11 16:21 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
> +// @ts-nocheck
Зачем добавил `ts-nocheck`? Что будет, если ты его удалишь? Давай, удалим его?

2022-10-11 16:22 UTC, yurijmikhalevich commented on the-list-ui/src/request-functions.js
> +}
Этот файл имеет отношение к PR?

2022-10-11 16:39 UTC, Roha990 commented on the-list-ui/src/request-functions.js
> +}
нет, он с ветки Данила ко мне пришел случайно

2022-10-11 16:54 UTC, Roha990 commented on the-list-ui/src/App.js
> +// @ts-nocheck
с ветки Данила ко мне пришел случайно

2022-10-11 17:33 UTC, yurijmikhalevich approved these changes
Отлично 👍 

В идеале, ещё бы при запуске приложения убеждаться, что у нас создан уникальный индекс по полю `date` в `attendance`: 
https://mongodb.github.io/node-mongodb-native/4.10/classes/Collection.html#createIndex

Это заметно ускорит выборку данных из БД по дате и гарантирует, что мы случайно не создадим две записи с одной и той же датой.

2022-10-11 19:30 UTC, OstaptsovDanil requested changes
Мне кажется, что нужно убрать `action` из JSON файла.
Если мы отправляем действие, то проверка будет со стороны клиента: если у него на экране нет галочки, то отправляется запрос с `add` и галочка добавляется. На мой взгляд, лучше сделать проверку на стороне сервера, убрать request.body.action и сделать проверку на наличие студента с нужным _id, если нет, то добавить, если есть - удалить.
Так мы сможем избежать ошибок, если, например, несколько человек одновременно отмечают студентов


UPD: Я проверил, все работает хорошо. Вообще, я поторопился с комментарием. Я так подумал, мой подход бы сделал ситуацию даже хуже

2022-10-11 19:55 UTC, OstaptsovDanil approved these changes
Узнал согласен

2022-10-11 20:30 UTC, EmmaMaltseva approved these changes
Одобряю изменения

2022-10-11 20:31 UTC, NSH4R approved these changes

2022-10-11 20:35 UTC, merged

2022-10-12 06:07 UTC, yurijmikhalevich commented
> На мой взгляд, лучше сделать проверку на стороне сервера, убрать request.body.action и сделать проверку на наличие студента с нужным _id, если нет, то добавить, если есть - удалить.
> Так мы сможем избежать ошибок, если, например, несколько человек одновременно отмечают студентов

`action` важен для того, чтобы программа вела себя нормально в ситуации, если несколько человек отмечают студентов.

Представь, что я и ты отмечаем, что Эмма пришла на занятие. Если мы оба шлём `"action": "add"`, сервер нормально схавает оба запроса и, в результате, Эмма будет отмечена как присутствующая.

Если мы не шлём `"action"` и запрос просто переключает студента из одного состояния в другое, то, в результате отправки двух наших запросов, Эмма будет сначала отмечена как присутствующая, потом обратно как отсутствующая.