[BE] Add function to get all students at the front-end
Move-Fast-and-Break-Things-Study-Group/the-list pull request #22
Opened 2022-10-05 20:10 UTC by OstaptsovDanil

## Что делает этот PR?

Подключает koa/cors к серверу 
Создает функцию для получения списка всех студентов со стороны фронта

## Ограничения

В функцию необходимо передавать адрес сервера для ее работы

## Как тестировать?

Необходимо запустить сервер и клиент. В консоли браузера будет выдан Promise с результатом работы функции. Если вы предварительно не заполните коллекцию студентов, то выведется пустой массив

## Чеклист

- [ ] мой PR сфокусирован и содержит одно логически цельное изменение
- [ ] я протестировал(а) PR локально и убедился(ась) в том, что он работает
- [ ] если моё изменение содержит изменения интерфейса, я вставил(а) в описание скриншот или скринкаст

2022-10-07 18:09 UTC, KogayIrina commented
1. Название PR не соответствует действительности. Написано: [BE] Add function to get all students at the front-end , при этом в твоем PR на беке реализовано удаление студентов. Соответствует приставке [BE], но не соответствует названию
2. Вывод списка студентов на фронтенде реализован, но тогда это не бьется с [BE]

Я бы разделила эти вещи на 2 раздельных пр, либо изменила название PR и сделала бы [BE][FE] Новое название пр

2022-10-07 18:50 UTC, OstaptsovDanil commented
> 1. Название PR не соответствует действительности. Написано: [BE] Add function to get all students at the front-end , при этом в твоем PR на беке реализовано удаление студентов. Соответствует приставке [BE], но не соответствует названию
> 2. Вывод списка студентов на фронтенде реализован, но тогда это не бьется с [BE]
> 
> Я бы разделила эти вещи на 2 раздельных пр, либо изменила название PR и сделала бы [BE][FE] Новое название пр

Но я не реализовывал удаление студентов на бэке, там просто несколько строк превратились в одну, возможно это сделала та штука для форматирования текста

Сама функция реализована в отдельном файле в директории `the-list\the-list-ui\src\request-functions.js` и используется в теле главной функции в файле App.js

2022-10-07 18:55 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  .use(router.allowedMethods());
Ещё один `app.use` штука для форматирования не стала бы добавлять (-: Похоже на плохо разруленный конфликт.

2022-10-07 19:21 UTC, OstaptsovDanil commented on the-list-be/server.js
> +  .use(router.allowedMethods());
Кажется я сначала начал ребейзить ветку под другую свою ветку, не смог отменить, закончил ребейз и отребейзил под Мейн, а этого не заметил

2022-10-07 19:29 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  .use(router.allowedMethods());
Бывает (-:

Если в процессе рибейза случился конфликт, то отменить рибейз можно, выполнив команду `git rebase --abort`.

2022-10-11 13:39 UTC, Roha990 commented on the-list-be/server.js
> +  .use(cors())
что делает `use(cors())`?

2022-10-11 13:42 UTC, Roha990 commented on the-list-ui/src/request-functions.js
> +    const response = await fetch(`${url}/students`, {
что здесь происходит?

2022-10-11 13:42 UTC, Roha990 commented on the-list-ui/src/App.js
> +  console.log(students);
`console.log(students)` убрать думаю стоит

2022-10-11 16:38 UTC, OstaptsovDanil commented on the-list-ui/src/App.js
> +  console.log(students);
Просто для демонстрации работы функции, она сама в html код ничего не выводит, но с ее помощью Никита будет делать вывод студентов

2022-10-11 17:36 UTC, yurijmikhalevich commented on the-list-ui/src/request-functions.js
> + */
Nice 👍

2022-10-11 17:38 UTC, yurijmikhalevich commented on the-list-ui/src/request-functions.js
> +    method: 'GET'
`GET` не метод по-умолчанию для `fetch`? Если так, то можно просто ```await fetch(`${url}/students`)``` написать 🤔

2022-10-11 17:39 UTC, yurijmikhalevich requested changes
Всё хорошо, но надо вернуть случайно удалённый `.prettierignore` + пара небольших комментариев.

2022-10-11 17:39 UTC, yurijmikhalevich commented on the-list-ui/.prettierignore 
> -coverage
Верни `.prettierignore` с `coverage` и `build` на место, пожалуйста :)

2022-10-11 17:44 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
> +  const backEndURL = 'http://localhost:4000';
```suggestion
  const backEndURL = process.env.REACT_APP_BACKEND_URL;
```

Чтобы это работало, надо создать в `the-list-ui` файлик `.env` и поместить в него:
```
REACT_APP_BACKEND_URL = http://localhost:4000
```

Это позволит нам поменять URL бакенда для продакшена отредактировав `.env`-файл и не внося правки в код.

Вы можете также иметь `.env.local` файл со своими локальными настройками. `.env.local` переопределяет `.env`. `.env.local` коммитить не надо.

2022-10-11 17:44 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
> +  const backEndURL = 'http://localhost:4000';
Также, можно эту константу сделать глобальной, вынести за пределы функции `App`.

2022-10-11 17:55 UTC, OstaptsovDanil commented on the-list-ui/.prettierignore 
> -coverage
ой а как они удалились

2022-10-11 17:56 UTC, OstaptsovDanil commented on the-list-ui/src/request-functions.js
> +    const response = await fetch(`${url}/students`, {
Отправляется запрос

2022-10-11 17:57 UTC, OstaptsovDanil commented on the-list-be/server.js
> +  .use(cors())
без него ответ сервера не доходит до клиента

2022-10-11 18:07 UTC, OstaptsovDanil commented on the-list-ui/src/App.js
> +  const backEndURL = 'http://localhost:4000';
.env файл надо создать в папке `the-list-ui`?

2022-10-11 19:09 UTC, Roha990 approved these changes, later dismissed
Проверил, вроде нормально работает

2022-10-13 07:00 UTC, yurijmikhalevich submitted a review, later dismissed

2022-10-13 07:01 UTC, yurijmikhalevich commented
Всё хорошо, но GitHub говорит, что есть конфликт с main'ом в .prettierignore. Рибейз должен помочь его решить.

2022-10-14 16:05 UTC, Roha990 commented on the-list-be/server.js
> +  const insertResult = await students.insertOne({ name: body.name });
назови переменную более понятно, `newStudent` например

2022-10-14 16:06 UTC, Roha990 commented on the-list-be/server.js
>    ctx.body = insertResult;
переменную по другому назови, не понятно что за ввод результата

2022-10-14 16:12 UTC, OstaptsovDanil commented on the-list-be/server.js
>    ctx.body = insertResult;
нет

2022-10-14 16:15 UTC, Roha990 approved these changes
Харош, надеюсь ребята на фронте справятся

2022-10-14 16:57 UTC, yurijmikhalevich approved these changes

2022-10-14 18:25 UTC, NSH4R approved these changes

2022-10-14 19:23 UTC, EmmaMaltseva commented on the-list-ui/src/request-functions.js
> + */
А зачем эта строчка. И почему она так оформлена?

2022-10-14 19:39 UTC, OstaptsovDanil commented on the-list-ui/src/request-functions.js
> + */
это говорит, что url это строка

2022-10-14 20:00 UTC, EmmaMaltseva approved these changes
Замечательно, надеюсь, фронт разберётся

2022-10-14 20:02 UTC, merged