Кнопка
Move-Fast-and-Break-Things-Study-Group/the-list pull request #23
Opened 2022-10-06 18:02 UTC by OstaptsovDanil

## Что делает этот PR?

Функция для добавления студента в БД
![image](https://user-images.githubusercontent.com/64201643/194385683-9ae03d45-2847-460d-bde5-cdf041ed5641.png)

## Ограничения

Кнопка не работает.
Функция по какой-то причине срабатывает трижды при запуске приложения

## Как тестировать?

Запусть сервер и клиент, просмотреть консоль браузера на ошибки, посмотреть список студентов через get-запрос в инсомнии

## Чеклист

- [ ] мой PR сфокусирован и содержит одно логически цельное изменение
- [ ] я протестировал(а) PR локально и убедился(ась) в том, что он работает
- [ ] если моё изменение содержит изменения интерфейса, я вставил(а) в описание скриншот или скринкаст

2022-10-07 07:08 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
> +        onClick={postStudents(backEndURL, "Button")}> Тыкалка </button>
Не надо привыкать писать `@ts-ignore`, надо читать, что линтер говорит. Линтер тут скажет тоже самое, что я в дискорде писал — в onClick надо передавать функцию, а ты передаёшь Promise.

```suggestion
        onClick={() => postStudents(backEndURL, "Button")}> Тыкалка </button>
```

2022-10-07 07:08 UTC, yurijmikhalevich requested changes
Надо починить код, отрибейзить на последний коммит в `main` и отформатировать код `npm run lint:fix` :)

2022-10-07 07:21 UTC, OstaptsovDanil commented on the-list-ui/src/App.js
> +        onClick={postStudents(backEndURL, "Button")}> Тыкалка </button>
Ааааааааааааааааааааааааааааааааааааа
так вот оно как. А я думал в смысле не функцию передал, если это функция

2022-10-07 18:01 UTC, KogayIrina requested changes

2022-10-07 18:01 UTC, KogaiIrina commented on the-list-ui/src/App.js
> +        <button
А ты запускал npm run lint:fix? Отступы поехали на 16 строке

2022-10-07 18:03 UTC, KogayIrina commented
нужно разрулить конфликты

2022-10-14 20:35 UTC, NSH4R approved these changes, later dismissed
.

2022-10-15 05:41 UTC, yurijmikhalevich requested changes

2022-10-15 05:41 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
>    const backEndURL = process.env.REACT_APP_BACKEND_URL;
Вынеси `backEndUrl` в `request-functions.js`, чтобы не было необходимости его передавать. И сделай его там глобальным, т.к. он общий для всех файлов.

Как-то так (глобальные константные переменные в JS традиционно пишутся капсом):

```js
const BE_URL = process.env.REACT_APP_BACKEND_URL;
```

2022-10-23 11:33 UTC, yurijmikhalevich requested changes
Сделай пожалуйста изменения, которые я прошу тут: https://github.com/Move-Fast-and-Break-Things-Study-Group/the-list/pull/23/files#r996257242.

Это позволит нам избавиться от необходимости передавать backend URL в каждый API метод.

2022-10-23 11:34 UTC, yurijmikhalevich commented on the-list-ui/src/request-functions.js
> +export async function postStudents(name, url = BE_URL) {
Здесь `url` аргумент он не нужен совсем.

```suggestion
export async function postStudents(name) {
```

2022-10-23 11:35 UTC, yurijmikhalevich commented on the-list-ui/src/request-functions.js
> +  await fetch(`${url}/students`, {
Аргумент `url` больше не нужен тут.

```suggestion
/**
 * @param {string} name
 */
export async function postStudents(name) {
  await fetch(`${BE_URL}/students`, {
```

2022-10-23 11:35 UTC, yurijmikhalevich commented on the-list-ui/src/request-functions.js
> +export async function getStudents(url = BE_URL) {
И тут.

```suggestion
export async function getStudents() {
```

2022-10-23 11:35 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
>    const backEndURL = process.env.REACT_APP_BACKEND_URL;
А отсюда `const backEndURL` нужно убрать.

2022-10-23 11:49 UTC, OstaptsovDanil commented
> Сделай пожалуйста изменения, которые я прошу тут: https://github.com/Move-Fast-and-Break-Things-Study-Group/the-list/pull/23/files#r996257242.
> 
> Это позволит нам избавиться от необходимости передавать backend URL в каждый API метод.

Вроде все сделал

2022-10-23 11:54 UTC, yurijmikhalevich approved these changes

2022-10-23 12:40 UTC, Roha990 approved these changes
Проверил, работает, харош

2022-10-23 13:00 UTC, KogayIrina approved these changes

2022-10-23 14:27 UTC, EmmaMaltseva approved these changes
Всё работает, спасибо за ответы в дискорде

2022-10-23 16:19 UTC, merged