[BE] editing a student's name
Move-Fast-and-Break-Things-Study-Group/the-list pull request #32
Opened 2022-10-15 08:37 UTC by Roha990

## Что делает этот PR?

Добавлена возможность редактировать имя студента
## Ограничения

## Как тестировать?

Для начала должен быть список студентов.
Для редактирование имени студента отправляет запрос в инсомнию `PATCH/'localhost:4000/students/Здесь_айдишник_студента' и пишите в JSON файл `"name":"Здесь_новое_имя"`
## Чеклист

- [ ] мой PR сфокусирован и содержит одно логически цельное изменение
- [ ] я протестировал(а) PR локально и убедился(ась) в том, что он работает
- [ ] если моё изменение содержит изменения интерфейса, я вставил(а) в описание скриншот или скринкаст

2022-10-15 08:40 UTC, Roha990 commented
почему-то у меня что-то делают коммиты Данила, ну ладно

2022-10-15 10:45 UTC, yurijmikhalevich requested changes
<img width="903" alt="image" src="https://user-images.githubusercontent.com/4187729/195982318-f79b0540-4a57-43f1-ba1c-8cbfb636656f.png">


Что-то не так с твоей веткой. Похоже, что ответвлялся от старого main, а не от самого нового. Отрибейзь, пожалуйста.

2022-10-15 10:46 UTC, yurijmikhalevich commented on the-list-be/server.js
> +});
Здесь не хватает проверки на то, что `body.name` не пустой. Посмотри, как Данил сделал такую проверку в операции создания студента.

2022-10-17 08:42 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  const newStudent = await students.insertOne({ name: body.name });
Твой PR всё ещё включает изменения Данила. Надо отрибейзиться на main.

2022-10-17 14:23 UTC, yurijmikhalevich approved these changes
LGTM 👍

2022-10-17 16:31 UTC, nsh4r approved these changes

2022-10-19 16:22 UTC, KogayIrina approved these changes

2022-10-22 11:03 UTC, EmmaMaltseva approved these changes
Мне нравится) Тестирование в инсомнии успешное

2022-10-23 09:17 UTC, merged