Интерфейс вывод списка студентов на экран.
Move-Fast-and-Break-Things-Study-Group/the-list pull request #33
Opened 2022-10-24 21:28 UTC by NSH4R

## Что делает этот PR?

Выводит список студентов на экран. 
![PR](https://user-images.githubusercontent.com/106260621/197632450-171af4af-8416-4821-8c31-4b8d8b909874.JPG)
## Ограничения

На данный момент доступен вывод только определенного списка, нужно создать запрос. 

## Чеклист

- [ ] мой PR сфокусирован и содержит одно логически цельное изменение
- [ ] я протестировал(а) PR локально и убедился(ась) в том, что он работает
- [ ] если моё изменение содержит изменения интерфейса, я вставил(а) в описание скриншот или скринкаст

2022-10-25 07:23 UTC, yurijmikhalevich requested changes
Давай сразу отправлять запрос на сервер для загрузки студентов и стилизуем интерфейс как на макете?

Запрос @OstaptsovDanil добавил в `request-functions.js`. Если сложно разобраться, сядьте, сделайте это с ним вместе.

Также, убедись, что вы с @EmmaMaltseva не делаете одинаковую работу: https://github.com/Move-Fast-and-Break-Things-Study-Group/the-list/pull/24.

Загружать данные удобнее всего будет так:
1. Установить и подключить react-query.
2. В компоненте
```js
const { data: students, error: studentsLoadingError } = useQuery('getStudents', getStudents);

// дальше можно рендерить students, в students будет массив студентов
// или в studentsLoadingError будет ошибка, которая возникла при попытке загрузить студентов,
// её можно вывести, если она не пустая
```

Если загружать студентов без `useQuery`, то это будет выглядеть примерно так:
```js
const [students, setStudents] = useState();
const [studentsLoadingError, setStudentsLoadingError] = useState();

useEffect(() => {
  getStudents()
    .then(setStudents)
    .catch(setStudentsLoadingError);
}, []);

// дальше можно рендерить students, в students будет массив студентов
// или в studentsLoadingError будет ошибка, которая возникла при попытке загрузить студентов,
// её можно вывести, если она не пустая
```

Недостатки второго варианта:
1. Мы не обрабатываем ситуации, когда компонент перестаёт рендерится или перерендеривается в момент отправки запроса, возможен баг тут.
2. Если нам надо будет получать список студентов в разных местах, с вариантом 2 будем слать несколько запросов, с `useQuery` — один, потому что он кеширует ответ.
3. В варианте 2, если нам надо перезагружать список студентов, надо писать дополнительную логику. В варианте 1 достаточно инвалидировать кеш `useQuery` для запроса.

@OstaptsovDanil, @NSH4R, `useQuery` здорово добавить в `request-functions.js`, чтобы не писать каждый раз.

2022-10-25 07:25 UTC, yurijmikhalevich commented
Ещё у тебя линтер не счастлив:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/4187729/197709825-600ec368-4605-4a03-a1d2-372b259ea101.png">

2022-10-25 15:37 UTC, KogayIrina requested changes

2022-10-25 15:37 UTC, KogayIrina commented on the-list-ui/src/App.js
> +//import { getStudents } from './request-functions.js';
Оставлять закомментированный код — моветон, его нужно либо удалить за ненадобностью, либо довести до необходимого состояния.

2022-10-25 15:37 UTC, KogaiIrina commented on the-list-ui/src/App.js
> +      {/* <hr className ='Line'> </hr> */}
Нам нужна эта строчка здесь?

2022-10-25 15:37 UTC, KogaiIrina commented on the-list-ui/src/App.js
> +  const students = [
Мы здесь забиваем гвоздь.
У нас есть готовый бэкенд, давай выводить реальных студентов :)

2022-10-25 15:37 UTC, KogayIrina commented on the-list-ui/src/App.js
> +  console.log(students);
лог нужно убрать

2022-10-26 08:30 UTC, Roha990 requested changes
Используй функции, сделанные Данилом

2022-10-28 12:13 UTC, OstaptsovDanil requested changes
не работает как надо

2022-10-29 17:02 UTC, KogayIrina approved these changes

2022-10-29 17:03 UTC, merged

2022-10-29 17:03 UTC, Roha990 approved these changes
харош