Начал работать над функцией удаления студентов для фронтенда
Move-Fast-and-Break-Things-Study-Group/the-list pull request #34
Opened 2022-10-30 20:10 UTC by Roha990

## Что делает этот PR?

Функция для удаление студента в БД

## Ограничения

На данный момент это просто кнопка для отправки одного конкретного запроса на сервер. В будущем фронтендерам надо будет полностью переработать эту кнопку используя данную функцию

## Как тестировать?

## Чеклист

- [ ] мой PR сфокусирован и содержит одно логически цельное изменение
- [ ] я протестировал(а) PR локально и убедился(ась) в том, что он работает
- [ ] если моё изменение содержит изменения интерфейса, я вставил(а) в описание скриншот или скринкаст

2022-10-31 05:28 UTC, KogayIrina commented
В пр затекли лишние изменения, нужно почистить

2022-10-31 07:19 UTC, yurijmikhalevich commented on the-list-be/server.js
> +router.delete('/students/', async ctx => {
Лучше
```suggestion
router.delete('/students/:id', async ctx => {
```

`body` обычно передают в `POST`, `PUT`, и `PATCH` запросах. Идентификатор ресурса во всех этих запросах чаще помещают в путь. Если нет причин не следовать стандартам, лучше их соблюдать. Так поддерживать продукт в дальнейшем будет проще.

2022-10-31 07:20 UTC, yurijmikhalevich commented on the-list-ui/src/request-functions.js
> +        body: JSON.stringify({ _id: id})
Этот метод тоже надо будет переделать так, чтобы он `id` передавал в пути, а не в `body`.

2022-10-31 07:22 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
> +      <button onClick={() => deleteStudents("635ed6328590391013135b64")}>Тыкалка тест для удаления</button>
Было бы идеально смёржить сначала PR данила, затем твой сверху на него, и переделать его так, чтобы он реально позволял удалять студентов.

Если мёржить только новый запрос в `request-functions.js`, то давай эту отладочную кнопку уберём.

2022-10-31 07:23 UTC, yurijmikhalevich requested changes
Несколько замечаний + картинки из PR надо убрать.

Давай в этом PR будем просто добавлять функцию в `request-functions.js`.

2022-11-01 07:09 UTC, yurijmikhalevich commented on the-list-be/server.js
> +    _id: new ObjectId(body.id)
```suggestion
    _id: new ObjectId(ctx.params.id)
```

2023-01-15 14:35 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
>          </form>
Нам не нужна форма, если всё что мы делаем — реагируем на клик по кнопке.

```suggestion
          <button
            onClick={() => deleteStudents('63c3d6708825941442769959')}
          >
            Тыкалка тест для удаления
          </button>
```

2023-01-15 14:35 UTC, yurijmikhalevich commented on the-list-ui/src/App.js
> +            name="delete_stud"
Посмеялся немного

stud — жеребец :)

2023-01-15 14:37 UTC, yurijmikhalevich commented on the-list-ui/src/api.js
> +    body: JSON.stringify({ _id: id })
Зачем нам передавать id студента в body, если мы уже передаём его в пути запроса?

Тут ⬇️
```js
await fetch(`${BE_URL}/students/${id}`
```

2023-01-15 14:39 UTC, yurijmikhalevich commented on the-list-be/server.js
> +  const { body } = ctx.request;
body не используется в этой функции, ниже ты достаёшь `id` из пути: `ctx.params.id`.
```suggestion
```

2023-01-15 14:39 UTC, yurijmikhalevich commented on the-list-ui/src/api.js
> +    body: JSON.stringify({ _id: id })
Я увидел, что body не используется на сервере.
```suggestion
    }
```

2023-01-25 09:33 UTC, yurijmikhalevich reviewed
Удали, пожалуйста, вот эти не используемые картинки и можно мёржить.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/4187729/214528085-18c7112e-ccb7-47bd-88e1-8dd7c507dd15.png">


<img width="309" alt="image" src="https://user-images.githubusercontent.com/4187729/214528108-272f5a99-8714-414c-aa93-4b641cc79602.png">

2023-01-25 09:53 UTC, yurijmikhalevich commented on the-list-ui/src/api.js
> +    }
```suggestion
    },
    body: JSON.stringify({ name: name })
```

2023-01-25 09:53 UTC, yurijmikhalevich commented on the-list-ui/src/api.js
> +    body: JSON.stringify({ _id: id })
```suggestion
    }
```

2023-01-25 10:16 UTC, yurijmikhalevich approved these changes

2023-01-26 17:23 UTC, EmmaMaltseva approved these changes

2023-01-29 15:14 UTC, merged