Интерфейс для input
Move-Fast-and-Break-Things-Study-Group/the-list pull request #38
Opened 2022-11-24 14:57 UTC by EmmaMaltseva

## Что делает этот PR?

Стилизация input

## Ограничения

1. При нажатии на иконку белого человека инпут должен активироваться, сейчас белая иконка играет роль отправки введенного значения на сервер
2. Сделать, чтобы кнопка добавления была слева от инпута 
3. Стилизовать галочку для отправки на сервер введенного значения

## Как тестировать?

Запустить бэк и фронт командой npm start, проверить работу кнопки и инпута

## Чеклист

- [ ] мой PR сфокусирован и содержит одно логически цельное изменение
- [ ] я протестировал(а) PR локально и убедился(ась) в том, что он работает
- [ ] если моё изменение содержит изменения интерфейса, я вставил(а) в описание скриншот или скринкаст

2022-11-25 05:57 UTC, KogayIrina requested changes

2022-11-25 05:57 UTC, KogayIrina commented on the-list-ui/src/components/Input.js
> +    var el = document.getElementById('input-person');
мы используем let или const.

const — для переменных, значения которых не должны меняться и let — для переменных, значения которых меняются.

2022-11-25 15:12 UTC, EmmaMaltseva commented on the-list-ui/src/components/Input.js
> +    var el = document.getElementById('input-person');
точно, извиняюсь, спасибо)

2022-11-25 19:45 UTC, KogayIrina requested changes

2022-11-25 19:45 UTC, KogaiIrina commented on the-list-ui/src/components/Input.js
> +    var el = document.getElementById('input-person');
еще, сразу не заметила, названия переменных должно быть понятным. Все элементы интерфейсы можно назвать el, но мы не будем их называть el1, el2, etc.
Поэтому лучше изменить название переменной на более подходящее.

2022-11-26 06:57 UTC, yurijmikhalevich commented on the-list-ui/src/components/Input.css
> +  background-image: url('./images/ok.png');
Можно ли использовать svg с Figma? Для простых элементов предпочтительнее svg потому что он мало весит и будет хорошо выглядеть при любом размере.

2022-11-26 07:02 UTC, yurijmikhalevich commented
https://www.loom.com/share/4beaac6665694bb392aeedbbdc7b33b0

2022-11-27 09:55 UTC, EmmaMaltseva commented on the-list-ui/src/components/Input.css
> +  background-image: url('./images/ok.png');
Спасибо! Не знала об этом)

2022-11-27 19:32 UTC, NSH4R approved these changes, later dismissed

2022-12-12 19:37 UTC, yurijmikhalevich approved these changes

2022-12-13 20:01 UTC, KogayIrina approved these changes

2022-12-17 09:20 UTC, Roha990 approved these changes
Круто, мне нравится

2022-12-26 18:18 UTC, OstaptsovDanil approved these changes

2022-12-26 18:24 UTC, NSH4R approved these changes

2022-12-27 16:36 UTC, merged